theme: minima
title: "MakeTables Documentation"
description: "A Python package for creating publication-ready tables from statistical models and descriptive statistics"
url: "https://dsliwka.github.io"
baseurl: "/maketables"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

header_pages:
  - index.md
  - examples.md
  - api.md

exclude:
  - .venv/
  - __pycache__/
  - *.pyc
  - .git/
  - .gitignore
  - setup.py
  - pyproject.toml
  - requirements*.txt
  - MANIFEST.in
  - LICENSE