project:
  type: website
  output-dir: _site

website:
  title: "MakeTables"
  description: "A Python package for creating publication-ready tables"
  navbar:
    left:
      - href: getting-started.ipynb
        text: Getting Started
      - href: ETable.ipynb
        text: Regressions
      - href: DTable.ipynb
        text: Descriptives
      - href: DocxTables.ipynb
        text: Word
      - href: LatexTables.ipynb
        text: LaTeX
      - href: WritingPapers.ipynb
        text: Writing Papers
      - text: Resources
        menu:
          - href: pystataIntegration.ipynb
            text: "Stata Integration"

    right:
      - icon: github
        href: https://github.com/dsliwka/maketables

format:
  html:
    theme: yeti
    toc: true
    code-copy: true
    code-fold: false
    html-table-processing: none
  
execute:
  freeze: auto

exclude:
  - "introductions.ipynb"
  - ".venv/"
  - "__pycache__/"
  - "mystuff/"
  - "docs/"