project:
  type: website
  output-dir: _site

website:
  title: "MakeTables"
  description: "A Python package for creating publication-ready tables"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: getting-started.ipynb
        text: Getting Started
      - href: ETable.ipynb
        text: Regression Tables
      - href: DTable.ipynb
        text: Descriptive Statistics
      - href: quartoExample.ipynb
        text: Using Quarto
    right:
      - icon: github
        href: https://github.com/dsliwka/maketables

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    code-copy: true
    code-fold: false
    html-table-processing: none

execute:
  freeze: auto

exclude:
  - "introductions.ipynb"
  - ".venv/"
  - "__pycache__/"
  - "mystuff/"